#!/bin/sh

#################
### AUTOSTART ###
#################

# Use the Dvorak layout and swap the Caps Lock and Escape keys
setxkbmap -layout us -variant dvorak -option caps:swapescape

# Enable Num Lock by default
numlockx on &

# Start the input method framework
fcitx5 -d &

# Start xscreensaver
xscreensaver --no-splash &

# Load the key mappings
pgrep -x sxhkd >/dev/null || sxhkd &

# Set the wallpaper and share its dominant colors with other apps
wal -R &

# Without this the bar does not launch
sleep 1

# Launch the bar
$HOME/.config/polybar/launch.sh

# Enable the compositor
pgrep -x picom >/dev/null || picom --experimental-backends --backend glx --xrender-sync-fence &

##################
### WORKSPACES ###
##################

bspc monitor -d home work dev chat media

#####################
### CONFIGURATION ###
#####################

# Borders
bspc config border_width 3
bspc config normal_border_color "#4c566a"
bspc config focused_border_color "#5e81ac"

# Spacing
bspc config window_gap 15
bspc config top_padding 0
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

# Split ratio
bspc config split_ratio 0.52

# Single window monocle
bspc config single_monocle true
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config top_monocle_padding 15

# Mouse manipulation
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

# Preselection feedback color
bspc config presel_feedback_color "#5e81ac"

#############
### RULES ###
#############

bspc rule -a ViberPC desktop=chat follow=on
bspc rule -a vlc desktop=media follow=on state=floating
